name: Copyright Updater

on: 
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Get list of changed files
        id: files
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }} >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Pass files to python script.
        run: |
          python ./tools/scripts/copyright_update.py "${{ env.CHANGED_FILES }}"
        continue-on-error: false # This is to stop git from pushing if there are no changes

      - name: Configure Git
        run: |
          git config --global user.name "copyright-bot"
          git config --global user.email "copyright-bot@users.noreply.github.com"
          
      - name: Add & Commit Changes
        run: |
          git add -A
          git diff --staged --quiet || git commit -m "Automatically update copyright notices [skip ci]"
          
      - name: Push changes
        run: |
          git push origin HEAD:${{ github.head_ref }}
