name: Copyright Updater

on: 
  pull_request:
    branches: [ci-test-branch]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@
        with:
          fetch-depth: 0

      - name: Get list of changed files
        id: files
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }} >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Pass files to python script.
        run: |
          python ./tools/scripts/copyright_update.py "${{ env.CHANGED_FILES }}"

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        run: |
          git add -A # Stages all changes; adjust if needed to target specific files
          git diff --staged --quiet || git commit -m "Automatically update copyright notices"
          git push origin HEAD:${{ github.head_ref }}
      
